### ISSUE TITLE
Mods for 0.14?

### ISSUE THREAD

**Issue by zhua-w** [stayintarkov/SIT-Mod-Ports#32]
Mods update for 0.14? MinimapSender is down..

**Comment by ChewieDM** [comment]
Mods will be updated once Server goes out of Bleeding Edge and has 100% mod support, some older mods may work with it and some don't. SIT 1.10.8824.27027 is a test release and to mods be ported, they need to be updated by their original creators.
Also, this is no Issue, feel free to ask any questions on [Discord](https://discord.gg/f4CN4n3nP2), not here.

**Comment by mihaicm93** [comment]
Not an issue, Closed

**Comment by zhua-w** [comment]
I should ask my questions on Discord, not here. Please accept my apology.
